package com.saez.aguita;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Build;
import android.os.Bundle;
import android.speech.RecognizerIntent;
import android.speech.tts.TextToSpeech;
import android.view.Gravity;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONObject;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class MainActivity extends Activity implements TextToSpeech.OnInitListener {
    private static final int SPEECH=9001,AUDIO=9002;
    private final int cream=Color.rgb(250,246,247), purple=Color.rgb(133,91,181), purpleDark=Color.rgb(79,54,112), text=Color.rgb(55,45,60), soft=Color.rgb(242,231,244), blue=Color.rgb(85,137,202);
    private LinearLayout root; private TextToSpeech tts; private TextView chatLog; private EditText chatInput; private int voiceMode=0;
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}    
    private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    private TextView tx(String s,int sp,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    private Button bt(String s,int c){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(17);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(bg(c,20));b.setMinHeight(dp(58));return b;}
    private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(18),dp(18),dp(18));c.setBackground(bg(Color.WHITE,24));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(14));c.setLayoutParams(p);c.setElevation(dp(2));return c;}

    @Override protected void onCreate(Bundle b){super.onCreate(b);Prefs.ensureDefaults(this);tts=new TextToSpeech(this,this);permissions();home();}
    @Override public void onInit(int s){if(s==TextToSpeech.SUCCESS){tts.setLanguage(new Locale("es","PE"));tts.setSpeechRate(.88f);tts.setPitch(.94f);}}
    @Override protected void onDestroy(){if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
    private void speak(String s){if(tts!=null)tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"susana");}
    private void permissions(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},55);}

    private void base(String title,String sub){ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.setBackgroundColor(cream);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(22),dp(18),dp(28));sv.addView(root);root.addView(tx(title,30,purpleDark,true));TextView st=tx(sub,14,Color.rgb(105,91,108),false);st.setPadding(0,dp(3),0,dp(16));root.addView(st);setContentView(sv);}
    private ImageView avatar(int size){ImageView i=new ImageView(this);i.setImageResource(R.drawable.susana_avatar);i.setScaleType(ImageView.ScaleType.CENTER_CROP);i.setBackground(bg(soft,100));i.setClipToOutline(true);i.setOutlineProvider(android.view.ViewOutlineProvider.BACKGROUND);i.setLayoutParams(new LinearLayout.LayoutParams(dp(size),dp(size)));return i;}
    private void nav(){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);String[] a={"Inicio","Hablar","Recordar","Perfil"};for(int i=0;i<4;i++){Button b=bt(a[i],Color.rgb(186,160,204));b.setTextSize(12);final int k=i;b.setOnClickListener(v->{if(k==0)home();else if(k==1)chat();else if(k==2)reminders();else profile();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(50),1);p.setMargins(dp(2),0,dp(2),0);n.addView(b,p);}root.addView(n);}

    private boolean birthday(){Calendar c=Calendar.getInstance();return c.get(Calendar.MONTH)==Calendar.DECEMBER&&c.get(Calendar.DAY_OF_MONTH)==6;}
    private void home(){base("SUSANA 💜","Tu compañera siempre: habla conmigo, cuéntame tu día o pídeme que recuerde algo.");LinearLayout h=card();h.setGravity(Gravity.CENTER_HORIZONTAL);h.addView(avatar(145));TextView hello=tx(birthday()?"¡Feliz cumpleaños, mi amor! 🎂💜":"Hola, mi amor 💜",25,purpleDark,true);hello.setGravity(Gravity.CENTER);hello.setPadding(0,dp(14),0,dp(5));h.addView(hello);TextView line=tx(birthday()?"Hoy quiero recordarte lo fuerte y especial que eres. Espero que te consientan mucho.":"Estoy aquí para escucharte y ayudarte con lo importante, sin complicarte con comandos.",16,text,false);line.setGravity(Gravity.CENTER);h.addView(line);Button talk=bt("🎙️ Hablar con Susana",purple);talk.setOnClickListener(v->{chat();startVoice(1);});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(16);h.addView(talk,p);Button rec=bt("🔔 Recuérdame algo",blue);rec.setOnClickListener(v->startVoice(2));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,-2);q.topMargin=dp(9);h.addView(rec,q);root.addView(h);
        LinearLayout quick=card();quick.addView(tx("Hoy contigo",20,purpleDark,true));quick.addView(tx("💧 Agua: "+Prefs.todayMl(this)+" / "+Prefs.targetMl(this)+" ml\n🔔 "+ReminderStore.count(this)+" recordatorio(s) guardados\n🎂 Cumpleaños: 6 de diciembre",15,text,false));Button water=bt("💧 Ya tomé un vaso",Color.rgb(76,151,203));water.setOnClickListener(v->{Prefs.addWater(this,Prefs.glass(this));Toast.makeText(this,"Bien hecho 💜",Toast.LENGTH_SHORT).show();home();});LinearLayout.LayoutParams wp=new LinearLayout.LayoutParams(-1,-2);wp.topMargin=dp(12);quick.addView(water,wp);root.addView(quick);nav();}

    private void chat(){base("Habla con SUSANA","Puedes escribir o hablar normalmente. No necesitas saber hacer prompts.");LinearLayout c=card();LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(avatar(58));TextView nm=tx("  SUSANA\n  Tu compañera siempre",16,purpleDark,true);head.addView(nm);c.addView(head);chatLog=tx("\nSusana: Hola, mi amor 💜. Cuéntame cómo estás o dime qué necesitas recordar.\n",16,text,false);chatLog.setLineSpacing(dp(5),1f);c.addView(chatLog);chatInput=new EditText(this);chatInput.setHint("Escribe como te salga...");chatInput.setTextColor(text);chatInput.setHintTextColor(Color.rgb(150,135,150));chatInput.setBackground(bg(soft,16));chatInput.setPadding(dp(14),dp(12),dp(14),dp(12));c.addView(chatInput);Button send=bt("Enviar",purple);send.setOnClickListener(v->send(chatInput.getText().toString()));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(9);c.addView(send,p);Button mic=bt("🎙️ Hablar",Color.rgb(198,100,142));mic.setOnClickListener(v->startVoice(1));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,-2);q.topMargin=dp(8);c.addView(mic,q);root.addView(c);nav();}
    private void append(String s){if(chatLog!=null)chatLog.append("\n"+s+"\n");}
    private void send(String raw){String m=raw==null?"":raw.trim();if(m.isEmpty())return;if(chatInput!=null)chatInput.setText("");append("Tú: "+m);if(tryReminder(m))return;String key=getPreferences(MODE_PRIVATE).getString("geminiKey","");if(key.isEmpty()){String r=local(m);append("Susana: "+r);speak(r);}else gemini(m,key);}
    private String local(String m){String x=m.toLowerCase(Locale.ROOT);if(x.contains("dolor")||x.contains("fibromialgia")||x.contains("cansad"))return "Te escucho, mi amor. Con dolor es válido bajar el ritmo. Si quieres, cuéntame qué necesitas hoy: desahogarte, organizar algo o simplemente compañía. Yo no reemplazo a tu médico ni a una psicóloga, pero sí puedo acompañarte.";if(x.contains("triste")||x.contains("llorar")||x.contains("sola"))return "Estoy aquí contigo 💜. No tienes que explicarlo perfecto. ¿Qué fue lo más pesado de hoy?";if(x.contains("bien")||x.contains("feliz")||x.contains("logr"))return "Eso merece celebrarse 💜. Cuéntame, ¿qué salió bien?";return "Te escucho, mi amor. Cuéntame un poquito más y vemos juntas qué puede ayudarte ahora.";}
    private void gemini(String m,String key){append("Susana: pensando…");new Thread(()->{try{URL u=new URL("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key="+key);HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json");c.setDoOutput(true);String prompt="Eres SUSANA, una compañera virtual cálida para una mujer adulta peruana con fibromialgia. Habla natural, breve, cariñosa y fuerte, como una figura materna de apoyo, pero NUNCA afirmes ser su madre fallecida ni una persona real. Escucha como un buen acompañante conversacional: valida emociones sin diagnosticar, ayuda a organizar pensamientos y sugiere apoyo profesional cuando corresponda. No reemplazas psicología ni medicina. Puedes llamarla 'mi amor' con moderación. Mensaje: "+m;JSONObject req=new JSONObject();JSONArray cont=new JSONArray();cont.put(new JSONObject().put("parts",new JSONArray().put(new JSONObject().put("text",prompt))));req.put("contents",cont);try(OutputStream os=c.getOutputStream()){os.write(req.toString().getBytes(StandardCharsets.UTF_8));}BufferedReader br=new BufferedReader(new InputStreamReader(c.getInputStream(),StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();String l;while((l=br.readLine())!=null)sb.append(l);JSONObject res=new JSONObject(sb.toString());String r=res.getJSONArray("candidates").getJSONObject(0).getJSONObject("content").getJSONArray("parts").getJSONObject(0).getString("text").trim();runOnUiThread(()->{append("Susana: "+r);speak(r);});}catch(Exception e){runOnUiThread(()->{String r=local(m);append("Susana: "+r);speak(r);});}}).start();}

    private void startVoice(int mode){voiceMode=mode;if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},AUDIO);return;}Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"es-PE");i.putExtra(RecognizerIntent.EXTRA_PROMPT,mode==2?"Dime qué quieres que te recuerde":"Te escucho...");try{startActivityForResult(i,SPEECH);}catch(Exception e){Toast.makeText(this,"No encontré reconocimiento de voz en este teléfono.",Toast.LENGTH_LONG).show();}}
    @Override protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r==SPEECH&&result==RESULT_OK&&data!=null){ArrayList<String> a=data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(a!=null&&!a.isEmpty()){String s=a.get(0);if(voiceMode==2){if(!tryReminder(s))manual(s);}else{if(chatInput!=null)chatInput.setText(s);send(s);}}}}

    private long parseWhen(String s){String x=s.toLowerCase(Locale.ROOT);Calendar c=Calendar.getInstance();Matcher w=Pattern.compile("en\\s+(\\d+)\\s+semana").matcher(x);Matcher d=Pattern.compile("en\\s+(\\d+)\\s+d[ií]a").matcher(x);if(w.find())c.add(Calendar.DAY_OF_MONTH,Integer.parseInt(w.group(1))*7);else if(d.find())c.add(Calendar.DAY_OF_MONTH,Integer.parseInt(d.group(1)));else if(x.contains("mañana"))c.add(Calendar.DAY_OF_MONTH,1);Matcher dm=Pattern.compile("(\\d{1,2})[/-](\\d{1,2})(?:[/-](\\d{2,4}))?").matcher(x);if(dm.find()){int day=Integer.parseInt(dm.group(1)),mon=Integer.parseInt(dm.group(2))-1,yr=dm.group(3)==null?c.get(Calendar.YEAR):Integer.parseInt(dm.group(3));if(yr<100)yr+=2000;c.set(yr,mon,day);}Matcher tm=Pattern.compile("(?:a las?|las)\\s*(\\d{1,2})(?::(\\d{2}))?\\s*(am|pm)?").matcher(x);if(!tm.find())return -1;int h=Integer.parseInt(tm.group(1)),m=tm.group(2)==null?0:Integer.parseInt(tm.group(2));String ap=tm.group(3);if("pm".equals(ap)&&h<12)h+=12;if("am".equals(ap)&&h==12)h=0;c.set(Calendar.HOUR_OF_DAY,h);c.set(Calendar.MINUTE,m);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);if(c.getTimeInMillis()<=System.currentTimeMillis()&&!x.contains("mañana")&&!w.find()&&!d.find()&&!dm.find())c.add(Calendar.DAY_OF_MONTH,1);return c.getTimeInMillis();}
    private int importance(String x){x=x.toLowerCase(Locale.ROOT);if(x.contains("essalud")||x.contains("cita")||x.contains("médic")||x.contains("medic")||x.contains("hospital")||x.contains("trámite")||x.contains("pago")||x.contains("examen"))return 3;if(x.contains("importante")||x.contains("medicina")||x.contains("reunión"))return 2;return 1;}
    private boolean tryReminder(String s){String x=s.toLowerCase(Locale.ROOT);if(!(x.contains("recu")||x.contains("avisa")||x.contains("recordatorio")||x.contains("alarma")))return false;long when=parseWhen(s);if(when<0)return false;String title=s.replaceAll("(?i)mamita|susana|recu[eé]rdame|hazme recordar|av[ií]same|ponme|una alarma|recordatorio"," ").replaceAll("\\s+"," ").trim();int imp=importance(s);long id=System.currentTimeMillis();ReminderStore.add(this,id,title,when,imp);SmartReminderScheduler.schedule(this,id,title,when,imp);String whenText=new SimpleDateFormat("dd/MM 'a las' HH:mm",Locale.getDefault()).format(new Date(when));String r="Listo, mi amor 💜. Te recordaré “"+title+"” el "+whenText+(imp>=3?". Como es importante, también te avisaré un día antes y tres horas antes.":imp==2?". También te avisaré tres horas antes.":".");if(chatLog!=null)append("Susana: "+r);Toast.makeText(this,"Recordatorio guardado 💜",Toast.LENGTH_LONG).show();speak(r);return true;}
    private void manual(String seed){final EditText e=new EditText(this);e.setHint("Ejemplo: cita en EsSalud 20/08 a las 9 pm");e.setText(seed);new AlertDialog.Builder(this).setTitle("¿Qué quieres recordar?").setView(e).setPositiveButton("Guardar",(d,w)->{String s="recuérdame "+e.getText().toString();if(!tryReminder(s))Toast.makeText(this,"No pude encontrar la hora. Prueba: 20/08 a las 9 pm",Toast.LENGTH_LONG).show();}).setNegativeButton("Cancelar",null).show();}

    private void reminders(){base("Mis recordatorios","Susana avisa con más anticipación cuando detecta algo importante.");LinearLayout c=card();c.addView(tx(ReminderStore.summary(this),16,text,false));Button b=bt("🎙️ Crear hablando",purple);b.setOnClickListener(v->startVoice(2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(8);c.addView(b,p);Button m=bt("✍️ Crear escribiendo",blue);m.setOnClickListener(v->manual(""));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,-2);q.topMargin=dp(8);c.addView(m,q);root.addView(c);nav();}
    private void profile(){base("Perfil y ajustes","Lo esencial, sin menús complicados.");LinearLayout c=card();c.setGravity(Gravity.CENTER_HORIZONTAL);c.addView(avatar(110));TextView n=tx("SUSANA\nTu compañera siempre",20,purpleDark,true);n.setGravity(Gravity.CENTER);n.setPadding(0,dp(10),0,dp(12));c.addView(n);c.addView(tx("🎂 Te felicitará cada 6 de diciembre.\n🔊 Voz más pausada y cálida usando la voz del teléfono.\n🔐 La clave de IA se guarda solo en este celular.\n🩺 Acompaña y organiza; no sustituye atención médica o psicológica.",15,text,false));Button key=bt("✨ Conectar IA para conversar mejor",purple);key.setOnClickListener(v->keyDialog());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(14);c.addView(key,p);root.addView(c);nav();}
    private void keyDialog(){EditText e=new EditText(this);e.setHint("Pega tu API Key de Gemini");e.setText(getPreferences(MODE_PRIVATE).getString("geminiKey",""));new AlertDialog.Builder(this).setTitle("IA de Susana").setMessage("La clave queda guardada localmente en este teléfono. No la subimos al repositorio.").setView(e).setPositiveButton("Guardar",(d,w)->{getPreferences(MODE_PRIVATE).edit().putString("geminiKey",e.getText().toString().trim()).apply();Toast.makeText(this,"Listo 💜",Toast.LENGTH_SHORT).show();}).setNegativeButton("Cancelar",null).show();}
}
